version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_file_sharing
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filesharing
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  weather-app:
    build: .
    container_name: file_sharing
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data/uploads:/app/uploads
    environment:
      - UPLOADS_DIR=/app/uploads
